name: Deploy
on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch:
  
jobs:
  build:
    name: Run Web App
    runs-on: ubuntu-latest
    steps:
      - name: Build Web App
        run: |
          echo "Build Web App"
          sleep 10s
      - uses: convictional/trigger-workflow-and-wait@v1.3.0
        with:
          owner: Akp-108
          repo: first-pipeline
          github_token: ${{ secrets.G_ACCESS_TOKEN }}
          workflow_file_name: data.yml
          ref: master  
      - name: Deploy Web App
        run: |
          echo "Deploy Web App"
          sleep 10s